version: "3.4"

services:
  xinfinnetwork:
    image: xinfinorg/xdposchain:v2.4.1
    volumes:
      - "./xdcchain:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
      - "./start-node.sh:/work/start.sh"
      - "./bootnodes.list:/work/bootnodes.list"
      - "./.pwd:/work/.pwd"
      - "/etc/localtime:/etc/localtime:ro"
    restart: "always"
    env_file: .env
    ports:
      - "30304:30303"
      - "8990:8545"
      - "8889:8546"
